import React from 'react';
import "./Survey.css";
import { Link } from "react-router-dom";
import logo2 from '../../images/EVONESIA putih fix 5.png';
import bingkaikiri from '../../images/Clone X 11.png';
import bingkaikanan from '../../images/Clone X 18.png';
function Survey() {
  return (
    <div className="main-survey">
      <img className='logo2' src={logo2} alt="" />
      <div id="menu">
        <div id="topmenu">
          <ul>
            <li><Link to='/Home'>Home</Link></li>
            <li><Link to='/Token'>Token</Link></li>
            <li><Link to='/Survey'>Survey</Link></li>
            <li><Link to='/Polling'>Polling</Link></li>
            <li><Link to='/'>Log Out</Link></li>
          </ul>
        </div>
      </div>
      <div className='tittlesurvey'>Survey</div>
      <div className='kiri'>
        <div className='bingkaikiri'></div>
        <img className='iconkiri' src={bingkaikiri} alt="" />
        <div className='namakiri'>Cadidate 1</div>
        <div className='katakiri'>Each character is entirely unique and is generated by combining
          attributes such as colour palettes, skin tones, facial traits, outfits and accessories.
          With nearly endless combinations, all characters are guaranteed to be one of a kind.</div>
        <div className='katakiri1'>Even though no two Tinyfaces will ever be the same, some variations are
          rarer than others. Watch out for special accessories and raw materials - the
          rarer the attributes, the rarer your character will be.</div>
        <div className='vimikiri'>VISI</div>
        <div className='vimikiri1'>MISI</div>
      </div>
      <div className='Tengah'>
        <div className='vimiatas'>VISI & MISI</div>
        <div className='katatengah'>Do you agree with both of them ?</div>
        <Link to='/Polling'><button type="submit" className="btn ">Agree, continue the selection</button></Link>
      </div>
      <div className='kanan'>
        <div className='bingkaikanan'></div>
        <img className='iconkanan' src={bingkaikanan} alt="" />
        <div className='namakanan'>Cadidate 2</div>
        <div className='katakanan'>Each character is entirely unique and is generated by combining attributes s
          uch as colour palettes, skin tones, facial traits, outfits and accessories.
          With nearly endless combinations, all characters are guaranteed to be one of a kind.</div>
        <div className='katakanan1'>Even though no two Tinyfaces will ever be the same, some variations are
          rarer than others. Watch out for special accessories and raw materials - the
          rarer the attributes, the rarer your character will be.</div>
        <div className='vimikanan'>VISI</div>
        <div className='vimikanan1'>MISI</div>
      </div>
    </div>
  )
}
export default Survey
