import React from 'react';
import "./Polling.css";
import { Form } from "react-bootstrap";
import { Link } from "react-router-dom";
import logo2 from '../../images/EVONESIA putih fix 5.png';
import bingkaikiripol from '../../images/Clone X 11.png';
import bingkaikananpol from '../../images/Clone X 18.png';


function Polling({ calon1, calon2, calon3, voting, handleRadio, pilih }) {

  const handleVote = (e) => {
    e.preventDefault();
    if (pilih.id !== 0) voting(Number(pilih));
    else window.alert("there is error in submission");
  };

  return (
    <>
      <div className="main-polling">
        <img className='logo2' src={logo2} alt="" />
        <div id="menu">
          <div id="topmenu">
            <ul>
              <li><Link to='/Home'>Home</Link></li>
              <li><Link to='/Token'>Token</Link></li>
              <li><Link to='/Survey'>Survey</Link></li>
              <li><Link to='/Polling'>Polling</Link></li>
              <li><Link to='/Logout'>Log Out</Link></li>
            </ul>
          </div>
        </div>
      </div><div className='tittlepolling'>Cadidate Vote</div>
      <Form onSubmit={handleVote}>
        <div className='kiripol'>
          <div className='bingkaikiripol'></div>
          <img className='iconkiripol' src={bingkaikiripol} alt="" />
          <div className='namakiripol'>Cadidate 1</div>
          <div className='katakiripol'>Each character is entirely unique and is generated by combining
            attributes such as colour palettes, skin tones, facial traits, outfits and accessories.
            With nearly endless combinations, all characters are guaranteed to be one of a kind.</div>
          <Link to='/Polling'><button type="submit" className="btn ">Click Here To Choose</button></Link>
        </div>
        <div className='kananpol'>
          <div className='bingkaikananpol'></div>
          <img className='iconkananpol' src={bingkaikananpol} alt="" />
          <div className='namakananpol'>Cadidate 2</div>
          <div className='katakananpol'>Even though no two Tinyfaces will ever be the same, some variations are
            rarer than others. Watch out for special accessories and raw materials - the
            rarer the attributes, the rarer your character will be.</div>
          <Link to='/Polling'><button type="submit" className="btn ">Click Here To Choose</button></Link>

        </div>
      </Form>
    </>
  )
}

export default Polling
